services:
  database:
    image: postgres:18
    container_name: complyx-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend
    expose:
      - "5432"

  api:
    build: https://github.com/styxiner/complyx-api.git
    container_name: complyx-api
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    ports:
      - "8080:8080"
    networks:
      - backend
    mem_limit: 4g
    cpus: "2.0"
    read_only: true
    tmpfs:
      - /tmp
volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
